CREATE TABLE customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    email      VARCHAR(255)
);

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    amount      DECIMAL(19, 2),
    status      VARCHAR(50)
);

CREATE TABLE payment (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    amount   DECIMAL(19, 2),
    status   VARCHAR(50)
);
